// Code generated by protoc-gen-go. DO NOT EDIT.
// source: record/pb/record.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_struct "github.com/golang/protobuf/ptypes/struct"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ListRecordsRequest struct {
	Base                 string   `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Table                string   `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRecordsRequest) Reset()         { *m = ListRecordsRequest{} }
func (m *ListRecordsRequest) String() string { return proto.CompactTextString(m) }
func (*ListRecordsRequest) ProtoMessage()    {}
func (*ListRecordsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9074497b9868df32, []int{0}
}

func (m *ListRecordsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRecordsRequest.Unmarshal(m, b)
}
func (m *ListRecordsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRecordsRequest.Marshal(b, m, deterministic)
}
func (m *ListRecordsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRecordsRequest.Merge(m, src)
}
func (m *ListRecordsRequest) XXX_Size() int {
	return xxx_messageInfo_ListRecordsRequest.Size(m)
}
func (m *ListRecordsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRecordsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRecordsRequest proto.InternalMessageInfo

func (m *ListRecordsRequest) GetBase() string {
	if m != nil {
		return m.Base
	}
	return ""
}

func (m *ListRecordsRequest) GetTable() string {
	if m != nil {
		return m.Table
	}
	return ""
}

type Records struct {
	Offset               string         `protobuf:"bytes,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Records              []*RecordModel `protobuf:"bytes,2,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Records) Reset()         { *m = Records{} }
func (m *Records) String() string { return proto.CompactTextString(m) }
func (*Records) ProtoMessage()    {}
func (*Records) Descriptor() ([]byte, []int) {
	return fileDescriptor_9074497b9868df32, []int{1}
}

func (m *Records) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Records.Unmarshal(m, b)
}
func (m *Records) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Records.Marshal(b, m, deterministic)
}
func (m *Records) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Records.Merge(m, src)
}
func (m *Records) XXX_Size() int {
	return xxx_messageInfo_Records.Size(m)
}
func (m *Records) XXX_DiscardUnknown() {
	xxx_messageInfo_Records.DiscardUnknown(m)
}

var xxx_messageInfo_Records proto.InternalMessageInfo

func (m *Records) GetOffset() string {
	if m != nil {
		return m.Offset
	}
	return ""
}

func (m *Records) GetRecords() []*RecordModel {
	if m != nil {
		return m.Records
	}
	return nil
}

type RecordModel struct {
	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields               *_struct.Struct `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *RecordModel) Reset()         { *m = RecordModel{} }
func (m *RecordModel) String() string { return proto.CompactTextString(m) }
func (*RecordModel) ProtoMessage()    {}
func (*RecordModel) Descriptor() ([]byte, []int) {
	return fileDescriptor_9074497b9868df32, []int{2}
}

func (m *RecordModel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordModel.Unmarshal(m, b)
}
func (m *RecordModel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordModel.Marshal(b, m, deterministic)
}
func (m *RecordModel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordModel.Merge(m, src)
}
func (m *RecordModel) XXX_Size() int {
	return xxx_messageInfo_RecordModel.Size(m)
}
func (m *RecordModel) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordModel.DiscardUnknown(m)
}

var xxx_messageInfo_RecordModel proto.InternalMessageInfo

func (m *RecordModel) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RecordModel) GetFields() *_struct.Struct {
	if m != nil {
		return m.Fields
	}
	return nil
}

func init() {
	proto.RegisterType((*ListRecordsRequest)(nil), "pb.ListRecordsRequest")
	proto.RegisterType((*Records)(nil), "pb.Records")
	proto.RegisterType((*RecordModel)(nil), "pb.RecordModel")
}

func init() { proto.RegisterFile("record/pb/record.proto", fileDescriptor_9074497b9868df32) }

var fileDescriptor_9074497b9868df32 = []byte{
	// 281 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xc9, 0xaa, 0x29, 0x4e, 0xc0, 0xc2, 0x50, 0x6a, 0x08, 0x1e, 0x4a, 0x4e, 0xd1, 0xc3,
	0x2e, 0xc4, 0x9b, 0x07, 0x2f, 0x9e, 0x84, 0xea, 0x21, 0x7d, 0x82, 0xdd, 0x66, 0x52, 0x16, 0x42,
	0x36, 0x66, 0x37, 0xa7, 0xd2, 0x8b, 0xaf, 0xe0, 0xa3, 0xf9, 0x0a, 0x3e, 0x88, 0x74, 0x37, 0x55,
	0xc1, 0xdb, 0xcc, 0xfc, 0xf3, 0xff, 0x33, 0x1f, 0x2c, 0x07, 0xda, 0x9a, 0xa1, 0x16, 0xbd, 0x12,
	0xa1, 0xe2, 0xfd, 0x60, 0x9c, 0x41, 0xd6, 0xab, 0xec, 0x66, 0x67, 0xcc, 0xae, 0x25, 0x21, 0x7b,
	0x2d, 0x64, 0xd7, 0x19, 0x27, 0x9d, 0x36, 0x9d, 0x0d, 0x1b, 0x3f, 0xaa, 0xef, 0xd4, 0xd8, 0x08,
	0xeb, 0x86, 0x71, 0xeb, 0x82, 0x9a, 0x3f, 0x02, 0xae, 0xb5, 0x75, 0x95, 0xcf, 0xb4, 0x15, 0xbd,
	0x8d, 0x64, 0x1d, 0x22, 0x9c, 0x2b, 0x69, 0x29, 0x8d, 0x56, 0x51, 0x71, 0x59, 0xf9, 0x1a, 0x17,
	0x70, 0xe1, 0xa4, 0x6a, 0x29, 0x65, 0x7e, 0x18, 0x9a, 0x7c, 0x0d, 0xb3, 0xc9, 0x8b, 0x4b, 0x88,
	0x4d, 0xd3, 0x58, 0x72, 0x93, 0x6d, 0xea, 0xf0, 0x16, 0x66, 0xe1, 0x65, 0x9b, 0xb2, 0xd5, 0x59,
	0x91, 0x94, 0x73, 0xde, 0x2b, 0x1e, 0x5c, 0x2f, 0xa6, 0xa6, 0xb6, 0x3a, 0xe9, 0xf9, 0x2b, 0x24,
	0x7f, 0xe6, 0x78, 0x05, 0x4c, 0xd7, 0x53, 0x1a, 0xd3, 0x35, 0x0a, 0x88, 0x1b, 0x4d, 0xad, 0x0f,
	0x8a, 0x8a, 0xa4, 0xbc, 0xe6, 0x81, 0x8d, 0x9f, 0xd8, 0xf8, 0xc6, 0xb3, 0x55, 0xd3, 0x5a, 0xb9,
	0x81, 0x38, 0xe4, 0xe1, 0x33, 0xc4, 0x4f, 0x03, 0x49, 0x47, 0xb8, 0x3c, 0x5e, 0xff, 0xcf, 0x9c,
	0x25, 0xbf, 0x5f, 0xd9, 0x3c, 0x7b, 0xff, 0xfc, 0xfa, 0x60, 0x8b, 0x7c, 0x2e, 0xf6, 0x47, 0xf8,
	0x83, 0xd8, 0x7b, 0xdc, 0xc3, 0x43, 0x74, 0xa7, 0x62, 0x7f, 0xed, 0xfe, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0x1a, 0xad, 0xdb, 0x6b, 0x93, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RecordClient is the client API for Record service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RecordClient interface {
	Create(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (*Records, error)
}

type recordClient struct {
	cc *grpc.ClientConn
}

func NewRecordClient(cc *grpc.ClientConn) RecordClient {
	return &recordClient{cc}
}

func (c *recordClient) Create(ctx context.Context, in *ListRecordsRequest, opts ...grpc.CallOption) (*Records, error) {
	out := new(Records)
	err := c.cc.Invoke(ctx, "/pb.Record/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RecordServer is the server API for Record service.
type RecordServer interface {
	Create(context.Context, *ListRecordsRequest) (*Records, error)
}

// UnimplementedRecordServer can be embedded to have forward compatible implementations.
type UnimplementedRecordServer struct {
}

func (*UnimplementedRecordServer) Create(ctx context.Context, req *ListRecordsRequest) (*Records, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}

func RegisterRecordServer(s *grpc.Server, srv RecordServer) {
	s.RegisterService(&_Record_serviceDesc, srv)
}

func _Record_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRecordsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RecordServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Record/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RecordServer).Create(ctx, req.(*ListRecordsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Record_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Record",
	HandlerType: (*RecordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Record_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "record/pb/record.proto",
}
